version: '3'

services:
  db:
    container_name: postgress-db
    image: postgres:alpine
    restart: always
    ports:
      - 5432
    volumes:
      - pg-data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - next-networks
  app:
    image: docker-next:1.0.0
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./pages:/usr/src/app/pages
      - ./public:/usr/src/app/public
      - ./prisma:/usr/src/app/prisma
      - ./styles:/usr/src/app/styles
    networks:
      - next-networks

volumes:
  pg-data:
networks:
  next-networks:
    driver: bridge
